version: '3.8'

services:
  db:
    image: mariadb
    container_name: baseclinica
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=clinica
      - MYSQL_PASSWORD=clinicadev
      - MYSQL_DATABASE=bdClinica
    volumes:
      - db-clinica:/var/lib/mysql
      - ./config/sql/:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadminclinica
    environment:
      - PMA_HOST=db
    ports:
      - "8083:80"
  laravel:
    build: 
      context: config/mvc
      dockerfile: Dockerfile
    command: /bin/bash -c "php artisan serve --host=0.0.0.0 --port=8000"
    ports:
      - "8000:8000"
    volumes:
      - ./mvc/src:/var/www/html
  vue:
    build: ./front
    command: /bin/bash -c "npm install && npm run dev"
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"  
    volumes:
      - ./front/:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  
  tomcat:
    container_name: tomcatclinica
    build:
      context: ./api
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
  composer:
    image: composer
    volumes:
      - ./mvc/src:/var/www/html  
  gateway:
    build: ./mvc
    expose:
      - 81
    ports:
      - "82:80"
      - "8001:8000"
    volumes:
      - ./mvc/src:/var/www/html  
volumes:
  db-clinica:
