version: '3.8'

services:
  db:
    image: mariadb
    volumes:
      - clinicallevant-db:/var/lib/mysql
      - ./config/sql/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=clinica
      - MYSQL_PASSWORD=clinicadev
      - MYSQL_DATABASE=bdclinica
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
    ports:
      - "8083:80"
  laravel:
    build: 
      context: config/mvc
      dockerfile: Dockerfile
    command: >
      sh -c "composer install && php artisan serve --host=0.0.0.0"
    #command: composer install && php artisan serve --host=0.0.0.0 
    ports:
      - "8007:8000"
    volumes:
      - ./mvc/src:/var/www/clinica
  vue:
    build: ./front
    command: /bin/bash -c "npm install && npm run dev"
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"  
    volumes:
      - ./front/:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  
  tomcat:
    container_name: tomcatclinica
    build:
      context: ./api
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
  composer:
    image: composer
    volumes:
      - ./mvc/src:/var/www/html  
  gateway:
    build: ./config
    expose:
      - 81
    ports:
      - "82:80"
      - "8001:8000"
    volumes:
      - ./mvc/src:/var/www/html  
volumes:
  clinicallevant-db:

